
var metaByFieldValue={

  "birthpath":{"label":"Birthpath: I am!",
    "1":"One: Decisive, courageous, leader, honest, active, dynamic, witty, impatient, innovative, independent, assertive, original, quick, inventive, mental, strong, principled",
    "2":"Two: Cooperative, tactful, patient, self-effacing, collector, understanding, timid, indecisive, sensitive, supportive, unassuming, diplomatic, quiet, listener",
    "3":"Three: expressive, social, charming, visionary, friendly, joyful, scattered, easygoing, joking, pleasure loving, artistic, optimistic, imaginative, gregarious, fun loving, persuasive, dramatic, generous",
    "4":"Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, stubborn, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "5":"Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sexual, impulsive",
    "6":"Six: domestic, nurturing, teacher, counselor, conventional, moral, consistent, generous, loyal, determined, compromising, judgmental, responsible, care giver, friendly, dependable, loving, practical, traditional",
    "7":"Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, aloof, solitary, eccentric, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "8":"Eight: Strong, forceful, money minded, decisive, authoritative, professional, blunt, masterful, problem solver, spiritual, demanding, powerful, ambitious, conservative, confident, efficient, formal, discerning, reliable",
    "9":"Nine: philosophical, wise, dramatic, religious, lover, tolerant, resourceful, intuitive, powerful, aloof, detached, fortunate, humanitarian, dreamer, poetic, generous, universal, dynamic, evolved, impressionable, global, distant",
    "11/2":"Eleven: inspirational, poetic, romantic, refined, aesthetic, famous, feminine, passive, intense, eccentric, fussy, worrisome, sensitive, achiever, celebrity, enthusiastic, idealistic, spiritual, imaginative, intuitive",
    "22/4":"Twenty two: masterful, builder, mission driven, intuitive, competent, visionary, efficient, expert, honest, hardworking, rational, leader, practical, spiritual, accomplished, powerful, assured, confident, worrisome",
    "33/6":"Thirty three: compassionate, teacher, wise, loving, caring, healer, care giver, judgmental, impulsive, visionary, creative, generous, creative, imaginative, playful, optimistic, friendly, storyteller, community builder",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "firstPinnacle":{"label":"Pinnacles: Events and Environments",
    "0":"",
    "1":"One:  You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance.",
    "2":"Two:  You are sensitive and supportive of people; you are learning the art and science of having patience. Interacting with people is very important to you. You are developing your understanding of spaces and timing.",
    "3":"Three:  You learning to be expressive, you are finding your voice; you are developing your artistic abilities. This is an easy time in your life being social and having fun. Creativity is very important.",
    "4":"Four:  You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "5":"Five:  You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products.",
    "6":"Six:  You will find yourself wanting to help and teach others. You feel responsible to do the right thing, this is a strong draw to marry and raise a family. You take on a role of service to your friends, family, and community. You develop a sense of justice.",
    "7":"Seven:  You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "8":"Eight:  You will find yourself gaining confidence in the world of business. You have a strong need to excel and manifest. You are in the energy of management and organization. Now is the ideal time to manage and grow your business to achieve success.",
    "9":"Nine:  You are learning the importance of staying present. You are spending too much time daydreaming and fantasying about the way your life should be lived. You have a strong desire to help the needy; you may find yourself volunteering. You are also drawn to travel globally; you have a strong interest in humanity.",
    "11/2":"Eleven:  You have a heightened sense of intuition, you are being asked to listen to your intuition and develop your sense of purpose. You become excited to explore the mysteries of the universe and share your knowledge.",
    "22/4":"Twenty-Two:  You have a heightened sense of responsibility and you know there is something you must accomplish in your lifetime.",
    "33/6":"Thirty-Three:   You have a strong desire to save the world, to heal the suffering. You may want to start a movement to rid the world of hunger. You may feel like you want to open a healing center. You have a strong sense of purpose.",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "secondPinnacle":{"label":"Pinnacles: Events and Environments",
    "0":"",
    "1":"One:  You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance.",
    "2":"Two:  You are sensitive and supportive of people; you are learning the art and science of having patience. Interacting with people is very important to you. You are developing your understanding of spaces and timing.",
    "3":"Three:  You learning to be expressive, you are finding your voice; you are developing your artistic abilities. This is an easy time in your life being social and having fun. Creativity is very important.",
    "4":"Four:  You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "5":"Five:  You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products.",
    "6":"Six:  You will find yourself wanting to help and teach others. You feel responsible to do the right thing, this is a strong draw to marry and raise a family. You take on a role of service to your friends, family, and community. You develop a sense of justice.",
    "7":"Seven:  You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "8":"Eight:  You will find yourself gaining confidence in the world of business. You have a strong need to excel and manifest. You are in the energy of management and organization. Now is the ideal time to manage and grow your business to achieve success.",
    "9":"Nine:  You are learning the importance of staying present. You are spending too much time daydreaming and fantasying about the way your life should be lived. You have a strong desire to help the needy; you may find yourself volunteering. You are also drawn to travel globally; you have a strong interest in humanity.",
    "11/2":"Eleven:  You have a heightened sense of intuition, you are being asked to listen to your intuition and develop your sense of purpose. You become excited to explore the mysteries of the universe and share your knowledge.",
    "22/4":"Twenty-Two:  You have a heightened sense of responsibility and you know there is something you must accomplish in your lifetime.",
    "33/6":"Thirty-Three:   You have a strong desire to save the world, to heal the suffering. You may want to start a movement to rid the world of hunger. You may feel like you want to open a healing center. You have a strong sense of purpose.",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "thirdPinnacle":{"label":"Pinnacles: Events and Environments",
    "0":"",
    "1":"One:  You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance.",
    "2":"Two:  You are sensitive and supportive of people; you are learning the art and science of having patience. Interacting with people is very important to you. You are developing your understanding of spaces and timing.",
    "3":"Three:  You learning to be expressive, you are finding your voice; you are developing your artistic abilities. This is an easy time in your life being social and having fun. Creativity is very important.",
    "4":"Four:  You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "5":"Five:  You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products.",
    "6":"Six:  You will find yourself wanting to help and teach others. You feel responsible to do the right thing, this is a strong draw to marry and raise a family. You take on a role of service to your friends, family, and community. You develop a sense of justice.",
    "7":"Seven:  You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "8":"Eight:  You will find yourself gaining confidence in the world of business. You have a strong need to excel and manifest. You are in the energy of management and organization. Now is the ideal time to manage and grow your business to achieve success.",
    "9":"Nine:  You are learning the importance of staying present. You are spending too much time daydreaming and fantasying about the way your life should be lived. You have a strong desire to help the needy; you may find yourself volunteering. You are also drawn to travel globally; you have a strong interest in humanity.",
    "11/2":"Eleven:  You have a heightened sense of intuition, you are being asked to listen to your intuition and develop your sense of purpose. You become excited to explore the mysteries of the universe and share your knowledge.",
    "22/4":"Twenty-Two:  You have a heightened sense of responsibility and you know there is something you must accomplish in your lifetime.",
    "33/6":"Thirty-Three:   You have a strong desire to save the world, to heal the suffering. You may want to start a movement to rid the world of hunger. You may feel like you want to open a healing center. You have a strong sense of purpose.",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "fourthPinnacle":{"label":"Pinnacles: Events and Environments",
    "0":"",
    "1":"One:  You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance.",
    "2":"Two:  You are sensitive and supportive of people; you are learning the art and science of having patience. Interacting with people is very important to you. You are developing your understanding of spaces and timing.",
    "3":"Three:  You learning to be expressive, you are finding your voice; you are developing your artistic abilities. This is an easy time in your life being social and having fun. Creativity is very important.",
    "4":"Four:  You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "5":"Five:  You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products.",
    "6":"Six:  You will find yourself wanting to help and teach others. You feel responsible to do the right thing, this is a strong draw to marry and raise a family. You take on a role of service to your friends, family, and community. You develop a sense of justice.",
    "7":"Seven:  You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "8":"Eight:  You will find yourself gaining confidence in the world of business. You have a strong need to excel and manifest. You are in the energy of management and organization. Now is the ideal time to manage and grow your business to achieve success.",
    "9":"Nine:  You are learning the importance of staying present. You are spending too much time daydreaming and fantasying about the way your life should be lived. You have a strong desire to help the needy; you may find yourself volunteering. You are also drawn to travel globally; you have a strong interest in humanity.",
    "11/2":"Eleven:  You have a heightened sense of intuition, you are being asked to listen to your intuition and develop your sense of purpose. You become excited to explore the mysteries of the universe and share your knowledge.",
    "22/4":"Twenty-Two:  You have a heightened sense of responsibility and you know there is something you must accomplish in your lifetime.",
    "33/6":"Thirty-Three:   You have a strong desire to save the world, to heal the suffering. You may want to start a movement to rid the world of hunger. You may feel like you want to open a healing center. You have a strong sense of purpose.",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },

  "firstChallenge":{"label":"Challenges: Inner Limitations",
    "0":"Zero:  Metaphysics teach that you create your own challenges. If you have a zero challenge at this time, it tells you that you have no outside challenges at this time in your life. If you find challenges, you need to own up to the source. . . YOU!",
    "1":"One:  You are learning survival skills. You may have a strong dominate parent that challenges you. You are learning to trust yourself. You may be dealing with handling some issues around your anger and quick temper.",
    "2":"Two:  Relationships are your teachers; you may be challenged to understand how to be in a happy, healthy relationship. You may find yourself frustrated with having to wait for others. You may not understand how to be a good partner.",
    "3":"Three:  You may not feel it is important to express yourself. You are challenged to communicate your feelings. You have a difficult time believing you have any creative abilities.",
    "4":"Four:  You feel trapped and restricted with routines and systems you are involved with. You have a difficult time following the rules; you don’t seem to be able to get out of the ruts you may have created.",
    "5":"Five:  You are restless and have a difficult time staying focused and completing tasks and projects. Your avant-guard attitude gets you into trouble. You feel trapped and crave freedom.",
    "6":"Six:  You may find that your commitments have caused you to become over loaded with responsibility. Your friends and family responsibilities may seem to consume too much of your personal time.",
    "7":"Seven:  You may find you have trust issues with people. You will be drawn to spend time alone with your thoughts. You may find yourself becoming isolated and or lonely. Superficial conversations bore you.",
    "8":"Eight:  You may find yourself spending lots of time at work. You are driven to accomplish and produce. You have a passion to create wealth at all costs. You may find yourself dominating your fellow workers if they can’t keep up the pace.",
    "9":"",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "secondChallenge":{"label":"Challenges: Inner Limitations",
    "0":"Zero:  Metaphysics teach that you create your own challenges. If you have a zero challenge at this time, it tells you that you have no outside challenges at this time in your life. If you find challenges, you need to own up to the source. . . YOU!",
    "1":"One:  You are learning survival skills. You may have a strong dominate parent that challenges you. You are learning to trust yourself. You may be dealing with handling some issues around your anger and quick temper.",
    "2":"Two:  Relationships are your teachers; you may be challenged to understand how to be in a happy, healthy relationship. You may find yourself frustrated with having to wait for others. You may not understand how to be a good partner.",
    "3":"Three:  You may not feel it is important to express yourself. You are challenged to communicate your feelings. You have a difficult time believing you have any creative abilities.",
    "4":"Four:  You feel trapped and restricted with routines and systems you are involved with. You have a difficult time following the rules; you don’t seem to be able to get out of the ruts you may have created.",
    "5":"Five:  You are restless and have a difficult time staying focused and completing tasks and projects. Your avant-guard attitude gets you into trouble. You feel trapped and crave freedom.",
    "6":"Six:  You may find that your commitments have caused you to become over loaded with responsibility. Your friends and family responsibilities may seem to consume too much of your personal time.",
    "7":"Seven:  You may find you have trust issues with people. You will be drawn to spend time alone with your thoughts. You may find yourself becoming isolated and or lonely. Superficial conversations bore you.",
    "8":"Eight:  You may find yourself spending lots of time at work. You are driven to accomplish and produce. You have a passion to create wealth at all costs. You may find yourself dominating your fellow workers if they can’t keep up the pace.",
    "9":"",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "thirdChallenge":{"label":"Challenges: Inner Limitations",
    "0":"Zero:  Metaphysics teach that you create your own challenges. If you have a zero challenge at this time, it tells you that you have no outside challenges at this time in your life. If you find challenges, you need to own up to the source. . . YOU!",
    "1":"One:  You are learning survival skills. You may have a strong dominate parent that challenges you. You are learning to trust yourself. You may be dealing with handling some issues around your anger and quick temper.",
    "2":"Two:  Relationships are your teachers; you may be challenged to understand how to be in a happy, healthy relationship. You may find yourself frustrated with having to wait for others. You may not understand how to be a good partner.",
    "3":"Three:  You may not feel it is important to express yourself. You are challenged to communicate your feelings. You have a difficult time believing you have any creative abilities.",
    "4":"Four:  You feel trapped and restricted with routines and systems you are involved with. You have a difficult time following the rules; you don’t seem to be able to get out of the ruts you may have created.",
    "5":"Five:  You are restless and have a difficult time staying focused and completing tasks and projects. Your avant-guard attitude gets you into trouble. You feel trapped and crave freedom.",
    "6":"Six:  You may find that your commitments have caused you to become over loaded with responsibility. Your friends and family responsibilities may seem to consume too much of your personal time.",
    "7":"Seven:  You may find you have trust issues with people. You will be drawn to spend time alone with your thoughts. You may find yourself becoming isolated and or lonely. Superficial conversations bore you.",
    "8":"Eight:  You may find yourself spending lots of time at work. You are driven to accomplish and produce. You have a passion to create wealth at all costs. You may find yourself dominating your fellow workers if they can’t keep up the pace.",
    "9":"",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "fourthChallenge":{"label":"Challenges: Inner Limitations",
    "0":"Zero:  Metaphysics teach that you create your own challenges. If you have a zero challenge at this time, it tells you that you have no outside challenges at this time in your life. If you find challenges, you need to own up to the source. . . YOU!",
    "1":"One:  You are learning survival skills. You may have a strong dominate parent that challenges you. You are learning to trust yourself. You may be dealing with handling some issues around your anger and quick temper.",
    "2":"Two:  Relationships are your teachers; you may be challenged to understand how to be in a happy, healthy relationship. You may find yourself frustrated with having to wait for others. You may not understand how to be a good partner.",
    "3":"Three:  You may not feel it is important to express yourself. You are challenged to communicate your feelings. You have a difficult time believing you have any creative abilities.",
    "4":"Four:  You feel trapped and restricted with routines and systems you are involved with. You have a difficult time following the rules; you don’t seem to be able to get out of the ruts you may have created.",
    "5":"Five:  You are restless and have a difficult time staying focused and completing tasks and projects. Your avant-guard attitude gets you into trouble. You feel trapped and crave freedom.",
    "6":"Six:  You may find that your commitments have caused you to become over loaded with responsibility. Your friends and family responsibilities may seem to consume too much of your personal time.",
    "7":"Seven:  You may find you have trust issues with people. You will be drawn to spend time alone with your thoughts. You may find yourself becoming isolated and or lonely. Superficial conversations bore you.",
    "8":"Eight:  You may find yourself spending lots of time at work. You are driven to accomplish and produce. You have a passion to create wealth at all costs. You may find yourself dominating your fellow workers if they can’t keep up the pace.",
    "9":"",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },

  "destiny":{"label":"Destiny:  You must become!",
    "0":"",
    "1":"One: Decisive, courageous, leader, honest, active, dynamic, witty, impatient, innovative, independent, assertive, original, quick, inventive, mental, strong, principled",
    "2":"Two: Cooperative, tactful, patient, self-effacing, collector, understanding, timid, indecisive, sensitive, supportive, unassuming, diplomatic, quiet, listener",
    "3":"Three: expressive, social, charming, visionary, friendly, joyful, scattered, easygoing, joking, pleasure loving, artistic, optimistic, imaginative, gregarious, fun loving, persuasive, dramatic, generous",
    "4":"Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, stubborn, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "5":"Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sexual, impulsive",
    "6":"Six: domestic, nurturing, teacher, counselor, conventional, moral, consistent, generous, loyal, determined, compromising, judgmental, responsible, care giver, friendly, dependable, loving, practical, traditional",
    "7":"Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, aloof, solitary, eccentric, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "8":"Eight: Strong, forceful, money minded, decisive, authoritative, professional, blunt, masterful, problem solver, spiritual, demanding, powerful, ambitious, conservative, confident, efficient, formal, discerning, reliable",
    "9":"Nine: philosophical, wise, dramatic, religious, lover, tolerant, resourceful, intuitive, powerful, aloof, detached, fortunate, humanitarian, dreamer, poetic, generous, universal, dynamic, evolved, impressionable, global, distant",
    "11/2":"Eleven: inspirational, poetic, romantic, refined, aesthetic, famous, feminine, passive, intense, eccentric, fussy, worrisome, sensitive, achiever, celebrity, enthusiastic, idealistic, spiritual, imaginative, intuitive",
    "22/4":"Twenty two: masterful, builder, mission driven, intuitive, competent, visionary, efficient, expert, honest, hardworking, rational, leader, practical, spiritual, accomplished, powerful, assured, confident, worrisome",
    "33/6":"Thirty three: compassionate, teacher, wise, loving, caring, healer, care giver, judgmental, impulsive, visionary, creative, generous, creative, imaginative, playful, optimistic, friendly, storyteller, community builder",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "realization":{"label":"Realization: What you will be",
    "0":"",
    "1":"One: decisive, courageous, leader, honest, active, dynamic, witty, impatient, innovative, independent, assertive, original, quick, inventive, mental, strong, principled",
    "2":"Two: cooperative, tactful, patient, self-effacing, collector, understanding, timid, indecisive, sensitive, supportive, unassuming, diplomatic, quiet, listener",
    "3":"Three: expressive, social, charming, visionary, friendly, joyful, scattered, easygoing, joking, pleasure loving, artistic, optimistic, imaginative, gregarious, fun loving, persuasive, dramatic, generous",
    "4":"Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, stubborn, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "5":"Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sexual, impulsive",
    "6":"Six: domestic, nurturing, teacher, counselor, conventional, moral, consistent, generous, loyal, determined, compromising, judgmental, responsible, care giver, friendly, dependable, loving, practical, traditional",
    "7":"Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, aloof, solitary, eccentric, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "8":"Eight: strong, forceful, money minded, decisive, authoritative, professional, blunt, masterful, problem solver, spiritual, demanding, powerful, ambitious, conservative, confident, efficient, formal, discerning, reliable",
    "9":"Nine: philosophical, wise, dramatic, religious, lover, tolerant, resourceful, intuitive, powerful, aloof, detached, fortunate, humanitarian, dreamer, poetic, generous, universal, dynamic, evolved, impressionable, global, distant",
    "11/2":"Eleven: inspirational, poetic, romantic, refined, aesthetic, famous, feminine, passive, intense, eccentric, fussy, worrisome, sensitive, achiever, celebrity, enthusiastic, idealistic, spiritual, imaginative, intuitive",
    "22/4":"Twenty two: masterful, builder, mission driven, intuitive, competent, visionary, efficient, expert, honest, hardworking, rational, leader, practical, spiritual, accomplished, powerful, assured, confident, worrisome",
    "33/6":"Thirty three: compassionate, teacher, wise, loving, caring, healer, care giver, judgmental, impulsive, visionary, creative, generous, creative, imaginative, playful, optimistic, friendly, storyteller, community builder",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "heartsDesire":{"label":"Heart’s Desire: You really want to be",
    "0":"",
    "1":"One: Decisive, courageous, leader, honest, active, dynamic, witty, impatient, innovative, independent, assertive, original, quick, inventive, mental, strong, principled",
    "2":"Two: Cooperative, tactful, patient, self-effacing, collector, understanding, timid, indecisive, sensitive, supportive, unassuming, diplomatic, quiet, listener",
    "3":"Three: expressive, social, charming, visionary, friendly, joyful, scattered, easygoing, joking, pleasure loving, artistic, optimistic, imaginative, gregarious, fun loving, persuasive, dramatic, generous",
    "4":"Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, stubborn, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "5":"Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sexual, impulsive",
    "6":"Six: domestic, nurturing, teacher, counselor, conventional, moral, consistent, generous, loyal, determined, compromising, judgmental, responsible, care giver, friendly, dependable, loving, practical, traditional",
    "7":"Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, aloof, solitary, eccentric, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "8":"Eight: Strong, forceful, money minded, decisive, authoritative, professional, blunt, masterful, problem solver, spiritual, demanding, powerful, ambitious, conservative, confident, efficient, formal, discerning, reliable",
    "9":"Nine: philosophical, wise, dramatic, religious, lover, tolerant, resourceful, intuitive, powerful, aloof, detached, fortunate, humanitarian, dreamer, poetic, generous, universal, dynamic, evolved, impressionable, global, distant",
    "11/2":"Eleven: inspirational, poetic, romantic, refined, aesthetic, famous, feminine, passive, intense, eccentric, fussy, worrisome, sensitive, achiever, celebrity, enthusiastic, idealistic, spiritual, imaginative, intuitive",
    "22/4":"Twenty two: masterful, builder, mission driven, intuitive, competent, visionary, efficient, expert, honest, hardworking, rational, leader, practical, spiritual, accomplished, powerful, assured, confident, worrisome",
    "33/6":"Thirty three: compassionate, teacher, wise, loving, caring, healer, care giver, judgmental, impulsive, visionary, creative, generous, creative, imaginative, playful, optimistic, friendly, storyteller, community builder",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "personality":{"label":"Personality: How others see you",
    "0":"",
    "1":"One: Decisive, courageous, leader, honest, active, dynamic, witty, impatient, innovative, independent, assertive, original, quick, inventive, mental, strong, principled",
    "2":"Two: Cooperative, tactful, patient, self-effacing, collector, understanding, timid, indecisive, sensitive, supportive, unassuming, diplomatic, quiet, listener",
    "3":"Three: expressive, social, charming, visionary, friendly, joyful, scattered, easygoing, joking, pleasure loving, artistic, optimistic, imaginative, gregarious, fun loving, persuasive, dramatic, generous",
    "4":"Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, stubborn, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "5":"Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sexual, impulsive",
    "6":"Six: domestic, nurturing, teacher, counselor, conventional, moral, consistent, generous, loyal, determined, compromising, judgmental, responsible, care giver, friendly, dependable, loving, practical, traditional",
    "7":"Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, aloof, solitary, eccentric, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "8":"Eight: Strong, forceful, money minded, decisive, authoritative, professional, blunt, masterful, problem solver, spiritual, demanding, powerful, ambitious, conservative, confident, efficient, formal, discerning, reliable",
    "9":"Nine: philosophical, wise, dramatic, religious, lover, tolerant, resourceful, intuitive, powerful, aloof, detached, fortunate, humanitarian, dreamer, poetic, generous, universal, dynamic, evolved, impressionable, global, distant",
    "11/2":"Eleven: inspirational, poetic, romantic, refined, aesthetic, famous, feminine, passive, intense, eccentric, fussy, worrisome, sensitive, achiever, celebrity, enthusiastic, idealistic, spiritual, imaginative, intuitive",
    "22/4":"Twenty two: masterful, builder, mission driven, intuitive, competent, visionary, efficient, expert, honest, hardworking, rational, leader, practical, spiritual, accomplished, powerful, assured, confident, worrisome",
    "33/6":"Thirty three: compassionate, teacher, wise, loving, caring, healer, care giver, judgmental, impulsive, visionary, creative, generous, creative, imaginative, playful, optimistic, friendly, storyteller, community builder",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "habitChallenge":{"label":"Habit Challenge: Stress causes you to",
    "0":"",
    "1":"One:  agitated, unrealistic, victim, over confident",
    "2":"Two:  shy, scared, withdrawn, helpless",
    "3":"Three:  Scattered, talkative, over optimistic, frivolous",
    "4":"Four:  stubborn, self-righteous, fixed mindset, narrow vision",
    "5":"Five:  unstable, restless, impatience, impetuous",
    "6":"Six:  justified, corrective, unsolicited advice, argumentative",
    "7":"Seven:  analytical, critical, suspicious, shut down",
    "8":"Eight:  bossy, dominate, directive, forceful",
    "9":"Nine:  impractical, dreamer, detached, over generous",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },

  "physicalPlane":{"label":"Physical Plane",
    "0":"",
    "1":"",
    "2":"",
    "3":"",
    "4":"",
    "5":"",
    "6":"",
    "7":"",
    "8":"",
    "9":"",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "mentalPlane":{"label":"Mental Plane",
    "0":"",
    "1":"",
    "2":"",
    "3":"",
    "4":"",
    "5":"",
    "6":"",
    "7":"",
    "8":"",
    "9":"",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "emotionalPlane":{"label":"Emotional Plane",
    "0":"",
    "1":"",
    "2":"",
    "3":"",
    "4":"",
    "5":"",
    "6":"",
    "7":"",
    "8":"",
    "9":"",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "spiritualPlane":{"label":"Spiritual Plane",
    "0":"",
    "1":"",
    "2":"",
    "3":"",
    "4":"",
    "5":"",
    "6":"",
    "7":"",
    "8":"",
    "9":"",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },

  "personalYear":{"label":"Personal Year:",
    "0":"",
    "1":"Number 1 - BE: Independent, assertive, original, quick, inventive, mental, strong, principled. DO: Start something new, create original ideas, be confident, take a leadership role, look at new aspects of old plans and ideas, be bold, listen to your intuition.",
    "2":"Number 2 - BE: Sensitive, supportive, unassuming, diplomatic, artistic, friendly, quiet, listener. DO: Take time out to rest and recuperate, learn patience, create relationships, be mindful and thoughtful, reflect, observe and experience, ponder your passion & purpose.",
    "3":"Number 3 - BE: Optimistic, imaginative, creative, gregarious, persuasive, dramatic, generous, playful. DO: Travel, play, flirt, be optimistic, entertain, be social, write, sing, draw, and paint. Time to network and market your products and services.",
    "4":"Number 4 - BE: Practical, sensible, rational, honest, realistic, loyal, hardworking, serious. DO: Time to plan your work and work your plan, make commitments and agreements, sign contracts, stay late and finish projects, work pays off with rewards of achievement.",
    "5":"Number 5 - BE: Adventurous, different, charismatic, persuasive, extroverted, sexual, impulsive, rebellious. DO: Expect change to show up unannounced, surprises may catch you off guard, be flexible and adaptable, travel, be dynamic, promote your products and services, you are magnetic.",
    "6":"Number 6 - BE: Responsible, care-giver, artistic, friendly, dependable, loving, practical, traditional. DO: Do domestic activities, spend time with family and friends, family and friends may demand more of your time, set boundaries, create more balance in your life, let your heart shine, people want to be with you now.",
    "7":"Number 7 - BE: Reserved, refined, studious, cautious, analytical, deep, selective, mystical. DO: Time to look for answers within, strong Spiritual connections, fate is at work now, meditate, journal, take a trip to reflect on who you are being.",
    "8":"Number 8 - BE: Powerful, ambitious, conservative, confident, efficient, formal, discerning, focused. DO: Excellent month for business and finance, be forceful to create win-win outcomes, apply yourself to the maximum, work with large projects and businesses.",
    "9":"Number 9 - BE: Humanitarian, dreamer, romantic, generous, evolved, impressionable, sensitive, dramatic. DO: Completion and transition are the key words, out with the old and make room for the new, think global, listen, share, reflect, respond, give, surrender, let go let GOD.",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "personalMonth":{"label":"Personal Month:",
    "0":"",
    "1":"Number 1 - BE: Independent, assertive, original, quick, inventive, mental, strong, principled. DO: Start something new, create original ideas, be confident, take a leadership role, look at new aspects of old plans and ideas, be bold, listen to your intuition.",
    "2":"Number 2 - BE: Sensitive, supportive, unassuming, diplomatic, artistic, friendly, quiet, listener. DO: Take time out to rest and recuperate, learn patience, create relationships, be mindful and thoughtful, reflect, observe and experience, ponder your passion & purpose.",
    "3":"Number 3 - BE: Optimistic, imaginative, creative, gregarious, persuasive, dramatic, generous, playful. DO: Travel, play, flirt, be optimistic, entertain, be social, write, sing, draw, and paint. Time to network and market your products and services.",
    "4":"Number 4 - BE: Practical, sensible, rational, honest, realistic, loyal, hardworking, serious. DO: Time to plan your work and work your plan, make commitments and agreements, sign contracts, stay late and finish projects, work pays off with rewards of achievement.",
    "5":"Number 5 - BE: Adventurous, different, charismatic, persuasive, extroverted, sexual, impulsive, rebellious. DO: Expect change to show up unannounced, surprises may catch you off guard, be flexible and adaptable, travel, be dynamic, promote your products and services, you are magnetic.",
    "6":"Number 6 - BE: Responsible, care-giver, artistic, friendly, dependable, loving, practical, traditional. DO: Do domestic activities, spend time with family and friends, family and friends may demand more of your time, set boundaries, create more balance in your life, let your heart shine, people want to be with you now.",
    "7":"Number 7 - BE: Reserved, refined, studious, cautious, analytical, deep, selective, mystical. DO: Time to look for answers within, strong Spiritual connections, fate is at work now, meditate, journal, take a trip to reflect on who you are being.",
    "8":"Number 8 - BE: Powerful, ambitious, conservative, confident, efficient, formal, discerning, focused. DO: Excellent month for business and finance, be forceful to create win-win outcomes, apply yourself to the maximum, work with large projects and businesses.",
    "9":"Number 9 - BE: Humanitarian, dreamer, romantic, generous, evolved, impressionable, sensitive, dramatic. DO: Completion and transition are the key words, out with the old and make room for the new, think global, listen, share, reflect, respond, give, surrender, let go let GOD.",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "personalDay":{"label":"Personal Day:",
"1":"Start something new, find a new interest or hobby, discover a new way to drive home.",
"2":"Meet someone for lunch, move furniture in your home, listen to your significant other.",
"3":"Take time to play, write in your journal, attend a creative workshop.",
"4":"Make plans, finish a project, work in the garden.",
"5":"Travel and explore, be competitive, think outside the box.",
"6":"Set healthy boundaries, offer advice, donate to a charity.",
"7":"Study something interesting, ask questions, be suspicious. ",
"8":"Push yourself, manifest your dreams, buy something of quality.",
"9":"Go to a museum, spend time with someone from a foreign country, dine a 5 star restaurant.",
"10":"Attend an inspirational class, ponder your purpose, get a psychic reading.",
"11":"Listen to your intuition, meditate, journal your thoughts.",
"12":"Go to a movie with a friend, write about a fun experience, take pictures.",
"13":"Remodel your home, rekindle a relationship, watch your health.",
"14":"Break the rules, travel somewhere new, entertain your friends.",
"15":"Have friends over for dinner, travel with family, learn something new.",
"16":"Listen closely, ask lots of questions, don’t take it personal.",
"17":"Invent something, research new ways to make money, promote something.",
"18":"Buy your friends dinner, travel overseas, give to your favorite charity.",
"19":"Take a leadership role, write something profound, and buy something of quality to wear.",
"20":"Attend a book club, ponder your future, Go dancing.",
"21":"Write a poem to a loved one, sing in the shower, dance in the rain.",
"22":"Plan a trip, create a collage, study an ancient culture.",
"23":"Hurry up and wait, play with a friend, take a risk.",
"24":"Plan a family gathering, go camping, plant some flowers.",
"25":"Keep a secret, start a diet, create a video.",
"26":"Buy a gift for your loved one, share insights with a friend, teach someone a skill.",
"27":"Watch a sci-fi movie, expose a fraud, and share a secret.",
"28":"Invest your savings, start a retirement plan, invest in yourself.",
"29":"Record your dreams; get a reading, study metaphysics.",
"30":"Write a self- help book, record yourself singing. Give a speech.",
"31":"Complete your to-do list, exercise, update your checkbook."
    },


  "count1":{"label":"1",
    "0":"You are not confident.",
    "1":"You are not confident.",
    "2":"You have an average amount of confidence.",
    "3":"You have an average amount of confidence.",
    "4":"You are confident; you have a desire to lead.",
    "5":"You are so confident that you don’t listen to others.",
    "6":"You are so confident that you don’t listen to others.",
    "7":"You are so confident that you don’t listen to others.",
    "8":"You are so confident that you don’t listen to others.",
    "9":"You are so confident that you don’t listen to others."
    },
  "count2":{"label":"2",
    "0":"You are impatient and have little follow-through to complete things.",
    "1":"You are patient and will cooperate.",
    "2":"You are patient and will cooperate."    },
  "count3":{"label":"3",
    "0":"You can be challenged with articulating what you mean.",
    "1":"You can be creative.",
    "2":"You can be creative.",
    "3":"You can be creative.",
    "4":"You have good communication skills; you are optimistic; you are creative.",
    "5":"You have good communication skills; you are optimistic; you are creative.",
    "6":"You have good communication skills; you are optimistic; you are creative.",
    "7":"You have good communication skills; you are optimistic; you are creative.",
    "8":"You have good communication skills; you are optimistic; you are creative.",
    "9":"You have good communication skills; you are optimistic; you are creative."
    },
  "count4":{"label":"4",
    "0":"You are not practical. If 4 is the only missing number, it is a sign of good health.",
    "1":"You are good at implementing other people’s ideas.",
    "2":"You are good at implementing other people’s ideas.",
    "3":"You are extremely practical; you are a hard worker.",
    "4":"You are extremely practical; you are a hard worker.",
    "5":"You are extremely practical; you are a hard worker.",
    "6":"You are extremely practical; you are a hard worker.",
    "7":"You are extremely practical; you are a hard worker.",
    "8":"You are extremely practical; you are a hard worker.",
    "9":"You are extremely practical; you are a hard worker."
    },
  "count5":{"label":"5",
    "0":"You are not competitive or curious.",
    "1":"You are not competitive or curious.",
    "2":"You are not competitive or curious.",
    "3":"You are flexible and adaptable.",
    "4":"You are flexible and adaptable.",
    "5":"You need lots of personal freedom. You have excellent sales ability.",
    "6":"You need lots of personal freedom. You have excellent sales ability.",
    "7":"You need lots of personal freedom. You have excellent sales ability.",
    "8":"You need lots of personal freedom. You have excellent sales ability.",
    "9":"You need lots of personal freedom. You have excellent sales ability."
    },
  "count6":{"label":"6",
    "0":"You will probably marry more than once.",
    "1":"You have good judgment; you rescue people.",
    "2":"You have good judgment; you rescue people.",
    "3":"You are traditional, opinionated, and loyal.",
    "4":"You are traditional, opinionated, and loyal.",
    "5":"You are traditional, opinionated, and loyal.",
    "6":"You are traditional, opinionated, and loyal.",
    "7":"You are traditional, opinionated, and loyal.",
    "8":"You are traditional, opinionated, and loyal.",
    "9":"You are traditional, opinionated, and loyal."
    },
  "count7":{"label":"7",
    "0":"You are open-minded; a tireless worker, you are curious.",
    "1":"You have exceptional memory and a spiritual interest.",
    "2":"You have exceptional memory and a spiritual interest",
    "3":"You are eccentric, analytical and aloof.",
    "4":"You are eccentric, analytical and aloof.",
    "5":"You are eccentric, analytical and aloof.",
    "6":"You are eccentric, analytical and aloof.",
    "7":"You are eccentric, analytical and aloof.",
    "8":"You are eccentric, analytical and aloof.",
    "9":"You are eccentric, analytical and aloof."
    },
  "count8":{"label":"8",
    "0":"People will offer to help you. Money is unimportant to you; it is for the higher purpose. If you are unattached to money it will magically come to you. You do something for the love of doing it not for the money it brings you.",
    "1":"You like to supervise people; you are reliable.",
    "2":"You are extremely hard working; you like to work with money.",
    "3":"You are extremely hard working; you like to work with money.",
    "4":"You are extremely hard working; you like to work with money.",
    "5":"You are extremely hard working; you like to work with money.",
    "6":"You are extremely hard working; you like to work with money.",
    "7":"You are extremely hard working; you like to work with money.",
    "8":"You are extremely hard working; you like to work with money.",
    "9":"You are extremely hard working; you like to work with money."
    },
  "count9":{"label":"9",
    "0":"You have trouble finishing projects.",
    "1":"You are compassionate; have idealistic goals; you enjoy romance.",
    "2":"You are compassionate; have idealistic goals; you enjoy romance.",
    "3":"You are compassionate; have idealistic goals; you enjoy romance.",
    "4":"You are compassionate; have idealistic goals; you enjoy romance.",
    "5":"You are compassionate; have idealistic goals; you enjoy romance.",
    "6":"You are extremely emotional and vulnerable to outside influences. You may be moody. You will do well to be careful about becoming narcissistic.",
    "7":"You are extremely emotional and vulnerable to outside influences. You may be moody. You will do well to be careful about becoming narcissistic.",
    "8":"You are extremely emotional and vulnerable to outside influences. You may be moody. You will do well to be careful about becoming narcissistic.",
    "9":"You are extremely emotional and vulnerable to outside influences. You may be moody. You will do well to be careful about becoming narcissistic."
    },
  "karmicLesson":{"label":"Karmic Lesson",
    "1":"One: Learn to be Independent, develop confidence, become a leader",
    "2":"Two: Learning about relationships will teach you your life lessons",
    "3":"Three: Learn to express your feelings, find your voice, express yourself",
    "4":"Four: Learn to apply yourself, understand structure, focus ",
    "5":"Five: Learn to be flexible and adaptable, take calculated risks",
    "6":"Six: Learn how to set boundaries, learn to receive, learn balance",
    "7":"Seven: Learn to trust, seek to understand the unseen world, develop intuition",
    "8":"Eight: Learn about the energy of money, learn about management energy",
    "9":"Nine: Learn about catch and release, learn about values, learn about reality"    },
  "findInput":{"label":""
    }
  };
/*
Two: Learning about relationships will teach you your life lessons
Three: Learn to express your feelings, find your voice, express yourself
Four: Learn to apply yourself, understand structure, focus
Five: Learn to be flexible and adaptable, take calculated risks
Six: Learn how to set boundaries, learn to receive, learn balance
Seven: Learn to trust, seek to understand the unseen world, develop intuition
Eight: Learn about the energy of money, learn about management energy
Nine: Learn about catch and release, learn about values, learn about reality
*/
/*
//unused meta fields
  "firstNameInput":{"label":"First Name"},
  "middleNameInput":{"label":"Middle Name"},
  "lastNameInput":{"label":"Last Name"},
  "birthdayInput":{"label":"Birthday"},
  "dayOfWeek":{"label":""},
  "dayOfYear":{"label":""},
  "firstName":{"label":"First Name"},
  "middleName":{"label":"Middle Name"},
  "lastName":{"label":"Last Name"},
  "dayOfBirth":{"label":"Day of Birth"},
  "firstChallenge":{"label":""},
  "secondPinnacle":{"label":""},
  "secondChallenge":{"label":""},
  "thirdPinnacle":{"label":""},
  "thirdChallenge":{"label":""},
  "fourthPinnacle":{"label":""},
  "fourthChallenge":{"label":""},

*/